### ISSUE TITLE
Captcha throws error

### ISSUE THREAD

**Issue by lewri** [K1rakishou/Kuroba-Experimental#1011]
On 1.3.32 trying to make a post/reply throws an error on the captcha of `Expected a string but was BOOLEAN at path $.ticket`. Error still triggering a rate limit detection.

Have tried on two different networks connections.

**Comment by lemon1198** [comment]
Getting the same

**Comment by K1rakishou** [comment]
It's already fixed in the beta version. Will release stable version today.

**Comment by gliffs** [comment]
> It's already fixed in the beta version. Will release stable version today.

I'm actually using beta, pixel 8 pro/Android 14, still getting the rate limit every time I try to reply to any thread

**Comment by K1rakishou** [comment]
The rate limit is not a bug of the client. You will get the same rate limits even in the browser.

**Comment by gliffs** [comment]
> The rate limit is not a bug of the client. You will get the same rate limits even in the browser.

a 60 second rate limit on my first post of the day, and every single post after that post regardless of time in between?

**Comment by K1rakishou** [comment]
Is it the same rate limit though? Does it show up in the captcha window?
