### ISSUE TITLE
New reply layout/toolbar/search/etc bugs mega thread

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#1029]
Post all the broken shit here.
Oh yeah, the database schema was changed so it's a good idea to make a backup before updating to this beta.
Also, these are not all of the improvements, this is just an initial version where everything seems to work. More stuff to come.

**Comment by alkamine** [comment]
For the past two updates, the application has been freezing for me whe I have been trying to submit a reply in a thread. This happens before the send button is pressed and even before text is entered sometimes. This results in requiring me to kill the application and start it again. this has never happened before the updates to the UI.

**Comment by a84r7a3rga76fg** [comment]
It was better before. Highlighting the text has become so much more difficult because of the implementation of the text magnifier. The side bar jump around like a frog.

**Comment by a84r7a3rga76fg** [comment]
It breaks the keyboard too. No longer suggests words because it defaults to numbers. Have to restart the app.

Change back to what it was before, this is ridiculous.

**Comment by K1rakishou** [comment]
@alkamine 

>For the past two updates, the application has been freezing for me whe I have been trying to submit a reply in a thread. 

I did some changes that may potentially fix this (I can't reproduce it locally so I can't test it). If this keeps happening then I will need:
1. A video of when this happens.
2. Logs taken right after this happens (or at most 5 minutes after).

@a84r7a3rga76fg 

>Highlighting the text has become so much more difficult because of the implementation of the text magnifier. The side bar jump around like a frog.

I made some changes so that drawer/thread pane cannot be opened by doing slide gestures inside of the reply layout. Should be easier to select text now.

>It breaks the keyboard too. No longer suggests words because it defaults to numbers. Have to restart the app.

I've switched the TextField which is used by ReplyInput to the new TextFieldV2 (from Compose) which doesn't have this problem. However, this text field doesn't support text colorization (yet). I will bring it back once they add support.

Try the latest beta.

**Comment by alkamine** [comment]
> @alkamine
> 
> > For the past two updates, the application has been freezing for me whe I have been trying to submit a reply in a thread.
> 
> I did some changes that may potentially fix this (I can't reproduce it locally so I can't test it). If this keeps happening then I will need:
> 
> 1. A video of when this happens.
> 2. Logs taken right after this happens (or at most 5 minutes after).
> 
> @a84r7a3rga76fg
> 
> > Highlighting the text has become so much more difficult because of the implementation of the text magnifier. The side bar jump around like a frog.
> 
> I made some changes so that drawer/thread pane cannot be opened by doing slide gestures inside of the reply layout. Should be easier to select text now.
> 
> > It breaks the keyboard too. No longer suggests words because it defaults to numbers. Have to restart the app.
> 
> I've switched the TextField which is used by ReplyInput to the new TextFieldV2 (from Compose) which doesn't have this problem. However, this text field doesn't support text colorization (yet). I will bring it back once they add support.
> 
> Try the latest beta.

Thanks, seems to have fixed most of it, I saw a ot of freezing when the back button was pressed to return to the catalog after making a post, now its about 50% of what it was. Still happnes though.

New issue though: the text in the comment field when replying to a post persists across posts (stays in the comment box) on the same thread. FOr example, If I reply "hello" to someone, the next time I go to post in that thread, the comment field shows 

>123456789 (previosuly replied to post number)
"hello"

can you get rid of this? its annoting to have to select and delete your previous comment tat youve already posted from a fresh reply/post

**Comment by K1rakishou** [comment]
@alkamine 

>I saw a ot of freezing when the back button was pressed to return to the catalog after making a post, now its about 50% of what it was. 

You mean like, you start sending a post and then go back to catalog before it finishes?

>can you get rid of this? its annoting to have to select and delete your previous comment tat youve already posted from a fresh reply/post

Yeah, I will fix it.

**Comment by alkamine** [comment]
New Bug idenified: Voice input via custom keyboards or voice input applications does not work. whatever you say is just ignored and not put into the reply/new post field

**Comment by alkamine** [comment]
> @alkamine
> 
> > I saw a ot of freezing when the back button was pressed to return to the catalog after making a post, now its about 50% of what it was.
> 
> You mean like, you start sending a post and then go back to catalog before it finishes?

or if you decide not to post, if you type something in the comment/reply field, and hit the android back button on the navigation bar, instead of taking you back to the catalog, it freezes the whole app

**Comment by a84r7a3rga76fg** [comment]
The inputted text multiples itself by two if 4chan rejects your post

**Comment by alkamine** [comment]
New problem: as of yesterday, about 50% of the time posts fail, and when they do, the text in the comment box is doubled if you try to post again, which then posts the same comment twice. the app is very broken as of now.= in regards to the coment box and overall stability

**Comment by buggerlol** [comment]
If you try to add a new file by tapping the paperclip, and then decide you don't want to attach a file and back out, this error pops up. There shouldn't be any error shown in this case.

![Screenshot_20240322_210231](https://github.com/K1rakishou/Kuroba-Experimental/assets/157192148/a1af9046-4ce1-4232-a0be-7a6b6bccb691)

Another issue: if you tap one of the images stored in the reply box to view the preview and the image is portrait oriented, it will only show a zoomed in segment of the center of the image, like so:
![Screenshot_20240322_210556](https://github.com/K1rakishou/Kuroba-Experimental/assets/157192148/03288842-f280-44ac-9464-6d0d0341541d)


Also, I can't figure out how to access the name and options fields with the new reply box.

> New problem: as of yesterday, about 50% of the time posts fail, 

I had posts failing with the old reply box, it's actually why I tried updating. The doubling of comments didn't happen, however.

**Comment by buggerlol** [comment]
On Samsung Galaxy S23+, using the default keyboard, swipe-typing in the reply box doesn't add spaces automatically after each word. (This is the default behavior for URL bars.)

**Comment by alkamine** [comment]
>Also, I can't figure out how to access the name and options fields with the new reply box
the new UI isnt intuitive at all, you have to swipe up from below on the right panel where the post and select image options are. the app is currently really broken, fails posting 5/10 times and then doubles the text.

**Comment by alkamine** [comment]
> If you try to add a new file by tapping the paperclip, and then decide you don't want to attach a file and back out, this error pops up. There shouldn't be any error shown in this case.
> 
> ![Screenshot_20240322_210231](https://private-user-images.githubusercontent.com/157192148/316205849-a1af9046-4ce1-4232-a0be-7a6b6bccb691.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODY2MDYsIm5iZiI6MTcxMTI4NjMwNiwicGF0aCI6Ii8xNTcxOTIxNDgvMzE2MjA1ODQ5LWExYWY5MDQ2LTRjZTEtNDIzMi1hMGJlLTdhNmI2YmNjYjY5MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMzE4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDk5YmFiMGU5MTlkYjNmNDY5ZTU5N2VhZGMzZjJkODgxZGM0OWI4NDAwOTI4MmQxYTY2ZTk0NjhmMjQyYjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-gdPMStFMes_gDQBWXIVUMEduIG6Ul7_Q9T9RjINc48)
> 
> Another issue: if you tap one of the images stored in the reply box to view the preview and the image is portrait oriented, it will only show a zoomed in segment of the center of the image, like so: ![Screenshot_20240322_210556](https://private-user-images.githubusercontent.com/157192148/316206629-03288842-f280-44ac-9464-6d0d0341541d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODY2MDYsIm5iZiI6MTcxMTI4NjMwNiwicGF0aCI6Ii8xNTcxOTIxNDgvMzE2MjA2NjI5LTAzMjg4ODQyLWYyODAtNDRhYy05NDY0LTZkMGQwMzQxNTQxZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMzE4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTJlZGVhOGVkMmFjMzNhYmM0ODg2OTBmZGUwYjFiMDBlMGY2ZDg5YjJhMGM2ZDBmOWI0Yzg4ZTJkY2FlM2NiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7kFTryGFPtzh0uCPHhJdfewGkamDnfjuT_cAkTG365c)
> 
> Also, I can't figure out how to access the name and options fields with the new reply box.
> 
> > New problem: as of yesterday, about 50% of the time posts fail,
> 
> I had posts failing with the old reply box, it's actually why I tried updating. The doubling of comments didn't happen, however.

the new UI isnt intuitive at all, you have to swipe up from below on the right panel where the post and select image options are. the app is currently really broken, fails posting 5/10 times and then doubles the text.

**Comment by K1rakishou** [comment]
Text doubling fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/b99530711e58b1ba3668549f8bb59491b15a7975

**Comment by alkamine** [comment]
> Text doubling fixed in [b995307](https://github.com/K1rakishou/Kuroba-Experimental/commit/b99530711e58b1ba3668549f8bb59491b15a7975)

Just checked and yes, thanks for the prompt fix. App is still crashing when the back button is pressed and the post dialog is open

**Comment by happapa** [comment]
The new reply box has broken Japanese input completely. Using the keyboard's suggestion bar is basically mandatory when writing Japanese. On Gboard, the suggestion bar refuses to show any suggestions at all. On Samsung Keyboard, the suggestions show, but tapping them doesn't actually write text into the box. I wouldn't be surprised if other foreign languages like Chinese were also broken.

**Comment by a84r7a3rga76fg** [comment]
Older layout didn't require the text editor to be maximized to upload files via URLs

**Comment by K1rakishou** [comment]
>Older layout didn't require the text editor to be maximized to upload files via URLs

Yeah, this is already fixed with the new toolbar.

**Comment by alkamine** [comment]
> > Older layout didn't require the text editor to be maximized to upload files via URLs
> 
> Yeah, this is already fixed with the new toolbar.

app is still freezing when the back button on the navigation bar is tapped to return to the catalog

**Comment by a84r7a3rga76fg** [comment]
Highlighting text is still impossible. It always assumes I'm doing the back button gesture which crashes the program.

**Comment by K1rakishou** [comment]
@a84r7a3rga76fg Do you have gesture navigation enabled in Android settings?

**Comment by a84r7a3rga76fg** [comment]
I do and I will not turn if off

**Comment by K1rakishou** [comment]
@alkamine 
Ok so I actually didn't manage to reproduce your issue, maybe it fixed itself. If not then I will need a video or something like that to see what's going on.

**Comment by alkamine** [comment]
New Issue: After latest update today, bottom navigation bar is totally gone, with no option to put it back in the settings. its now permanently in the pullable section with the hamburger menu.

Can you please add an option to put it back? I cannot navigate with the new UI.

**Comment by K1rakishou** [comment]
Bookmarks and global search will eventually be moved to other more easily accessible places, so shouldn't be an issue.

**Comment by alkamine** [comment]
> Bookmarks and global search will eventually be moved to other more easily accessible places, so shouldn't be an issue.

As of now the ui takes many more steps to navigate what was once a one click process to check the threads you are participating in, and respond to replies etc. its a two handed job now on some phones for some users, like the previous generation Pixels with a curved screen on the sides because reaching over to the hamburger menu with your thumb doesnt trigger it because of the curve.

**Comment by K1rakishou** [comment]
@alkamine 
You can just swipe from left to right in the middle of the screen to open the drawer. But this only works in catalogs. In threads you can longtap the left edge and then drag to the right.

**Comment by alkamine** [comment]
> @alkamine You can just swipe from left to right in the middle of the screen to open the drawer. But this only works in catalogs. In threads you can longtap the left edge and then drag to the right.

its still an addition of more unneeded steps. And again, some of us have curved screens, which are hard to accurately tap on the edges. it used to be a single tap. What is the reason the UI is no longer configurable in this regard?

**Comment by K1rakishou** [comment]
@alkamine 
If you mean accessing bookmarks/global search now takes more clicks then it will be fixed eventually. The bookmarks will be merged into the drawer and global search will be a part of the catalog search. It will take some time, though, because it's a lot of work.

**Comment by alkamine** [comment]
> @alkamine If you mean accessing bookmarks/global search now takes more clicks then it will be fixed eventually. The bookmarks will be merged into the drawer and global search will be a part of the catalog search. It will take some time, though, because it's a lot of work.

Why isnt there an option to set the UI back to how it was? it should be trivial. I would just downgrade but the exports of the new version, with all my filters and other configurations are not compatible with the previous version. no idea why you did that either. really hampers the user experience, they cant go back even if they wanted to.

**Comment by Nekudot** [comment]
I don't want to make a new issue for this, and I think it can go here, so... the small notification number by the back button now shows all replies from all bookmarked threads instead of only (You)s, surely that's not intended, right?

Edit: I noticed the number is yellow and becomes orange when you have a reply, at least on the theme I'm using, so now I know it's not a bug. A bit misleading and very distracting compared to how it worked before

**Comment by K1rakishou** [comment]
@Nekudot 
That's how it worked before, though.

**Comment by Nekudot** [comment]
@K1rakishou 
This is what I mean, on the left is an old screenshot from last year, in the middle is a random screenshot from a month or so ago, and on the right is how it appears today. I didn't even remember there used to be a number, because it was pretty muted. In both the left and middle images, the number becomes bright when you have a reply, but now it always has this bright background under it, and it barely changes color when you receive a reply. It's not that big of a deal, but it did change after the latest update.
![ResizedImage_2024-05-04_04-19-45_2572](https://github.com/K1rakishou/Kuroba-Experimental/assets/16191641/8862bb60-6801-4f86-b92c-1149a1cb743c)

Edit: Thanks, I set bookmark_counter_normal_color in the theme to a more subdued color and has_replies_color to a brighter one. Good enough for me. I tried transparent too but it obviously got rid of the reply numbers in the bookmarks as well.

**Comment by K1rakishou** [comment]
Oh I see what you mean. Yeah, I did change the colors. Now it uses the same colors as the numbers of read/unread bookmarks on the Bookmarks screen/drawer. These three:
```
  val bookmarkCounterNotWatchingColor: Int,
  val bookmarkCounterHasRepliesColor: Int,
  val bookmarkCounterNormalColor: Int,
```
Previously it used transparent black color when there are no reply and theme's accent color when there are replies.

**Comment by cm-mc** [comment]
Sirry but it's a complete mess over here; can't post because this crazy shit I've never seen before is now blocking the comments box controls.
Can't change settings, because bottom bar isn't showing when pulling down.
Simply put, it's completely unusable as it is and won't even be able to update because i can't reach settings anymore.
Android 10 galaxy, btw.
![20240521_032850](https://github.com/K1rakishou/Kuroba-Experimental/assets/11512937/9c1fd0c2-c096-417f-8120-738a4028c177)
...

**Comment by obscenelyvague** [comment]
Search is completely broken on newer updates. 
When a keyword is searched, it also highlights non-matching parts if you scroll up or down
![1 (1)](https://github.com/K1rakishou/Kuroba-Experimental/assets/36733368/0af01ae6-5c97-46be-93f4-72becc164924)
(Notice ending of last lines on top two threads being highlighted)
It also only highlights the first keyword-matched thread, others get lost in the mix.
I have to go into the filtered window by pressing "1/(n)" at the top right to find the actual keyword matched threads. This is pretty horrible UX. Why do I have to press to open another window to show search specific threads? Previously it filtered non-matching threads on the main screen. 
![2 (1)](https://github.com/K1rakishou/Kuroba-Experimental/assets/36733368/e70028b7-32d7-470d-919f-5572c5452ca7)

**Comment by obscenelyvague** [comment]
Some new components don't really fit in with the rest of the app's theme in my opinion.

1. Option to hide the scrollbar was removed with the import of new scrollbar. I tried hiding it with the theming option by dropping alpha but that only lasts for the first launch and as long as app is in memory. If the app is restarted, the scrollbar theming gets reset to default. Can the option to hide scrollbar be brought back?

2. These new accented buttons don't adapt well to most themes and stick out like a sore thumb 
![a](https://github.com/K1rakishou/Kuroba-Experimental/assets/36733368/843c56d1-ebc7-4614-8899-3a38983701da)
Other buttons don't have an accented background
![b](https://github.com/K1rakishou/Kuroba-Experimental/assets/36733368/7fe13cae-d483-471d-8961-44c16497cafb)
Would probably be better if the accented background boxes were removed.

**Comment by i-just-lizard** [comment]
![image](https://github.com/K1rakishou/Kuroba-Experimental/assets/33904988/a07a2ec1-8f61-4ab2-aaca-05903684bb42)
It seems 2ch.hk captcha doesn't fit.
Was able to post once by rotating device sideways and reloading captcha till I get one slightly tilted to the right.

**Comment by MisterTwelve** [comment]
I am unable to post at all on the beta version with the new layout. The section to the right of the text box, where the submit and captcha buttons are, has a constant animation of arrows pointing upward which I'd assume is it loading something. Thing is, it never finishes that something, even if I let it sit undisturbed for 10 minutes straight.
I'm on a Galaxy S8.
