### ISSUE TITLE
Frequent ANR and crash

### ISSUE THREAD

**Issue by cdr9042** [K1rakishou/Kuroba-Experimental#1046]
After updating to the latest beta, I've been getting App not responding very often. Clearing cache, restart phone, nothing worked.

My phone is Mi 11 lite 5G, android 13, miui 14.0.6

What happened: 
- I open the app.
- the app show the icon loading, the header and footer show.
- App not responding after some seconds stuck at that screen.

Sometimes, the app opens and load successfully without ANR, I don't know why it sometimes work, sometimes doesn't.

And sometimes it crash with this:

Exception: java.lang.IllegalStateException
Message: SiteManager is not ready yet! Use awaitUntilInitialized()

Stacktrace
```
java.lang.IllegalStateException: SiteManager is not ready yet! Use awaitUntilInitialized()
	at com.github.k1rakishou.chan.core.manager.SiteManager.firstActiveSiteOrNull(SourceFile:171)
	at com.github.k1rakishou.chan.core.site.SiteResolver.findSiteForUrl(Unknown Source:65)
	at com.github.k1rakishou.chan.core.base.okhttp.CloudFlareHandlerInterceptor.interceptInternal(SourceFile:34)
	at com.github.k1rakishou.chan.core.base.okhttp.CloudFlareHandlerInterceptor.intercept(SourceFile:1)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:121)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:97)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

Logs
```
[D] 17:14:51.909 Dependency Injection Using HTTP_1_1
[D] 17:14:51.914 ThemeParser Theme (/data/user/0/com.github.k1rakishou.chan.beta/files/kurobaex_theme_dark.json) does not exist on the disk
[D] 17:14:51.914 ThemeParser Theme (/data/user/0/com.github.k1rakishou.chan.beta/files/kurobaex_theme_light.json) does not exist on the disk
[D] 17:14:51.915 ChanPostRepository ChanPostRepository.initialize()
[D] 17:14:51.916 SiteManager SiteManager.initialize()
[D] 17:14:51.917 BoardManager BoardManager.initialize()
[D] 17:14:51.917 SiteManager loadSitesInternal() start
[D] 17:14:51.917 BookmarksManager BookmarksManager.initialize()
[D] 17:14:51.917 BoardManager loadBoardsInternal() start
[D] 17:14:51.917 HistoryNavigationManager HistoryNavigationManager.initialize()
[D] 17:14:51.917 BookmarkWatcherCoordinator BookmarkWatcherCoordinator.initialize()
[D] 17:14:51.917 BoardManager loadBoardsInternal() siteDataListAsync.get() start
[D] 17:14:51.917 FilterWatcherCoordinator FilterWatcherCoordinator.initialize()
[D] 17:14:51.917 ArchivesManager ArchivesManager.initialize()
[D] 17:14:51.917 BookmarksManager initializeBookmarksInternal() start
[D] 17:14:51.917 ChanFilterManager ChanFilterManager.initialize()
[D] 17:14:51.918 Chan Application initialization took 36ms
[D] 17:14:51.918 ArchivesManager initializeArchivesManagerInternal() start
[D] 17:14:51.918 ChanFilterManager loadFiltersInternal() start
[D] 17:14:51.921 ArchivesManager SuspendableInitializer initWithModularResult() called
[D] 17:14:51.921 ArchivesManager SuspendableInitializer initWithValue() called
[D] 17:14:51.922 ArchivesManager notifyAllWaiters throwable==null: true, waiters=0
[D] 17:14:51.922 ArchivesManager SuspendableInitializer initWithValue() done
[D] 17:14:51.922 ArchivesManager initializeArchivesManagerInternal() done. Loaded 13 archives
[D] 17:14:51.922 ArchivesManager initializeArchivesManagerInternal() end, took 3.858958ms
[D] 17:14:51.938 StartActivity onCreate() start isFreshStart: true, initializing everything
[D] 17:14:51.958 ChanPostRepository Not enough posts to start deleting, posts in database amount: 10815, max allowed posts amount: 75000
[D] 17:14:51.992 NavigationControllerContainerLayout initThreadControllerTracking()
[D] 17:14:51.997 NavigationControllerContainerLayout initThreadControllerTracking()
[D] 17:14:51.997 ControllerNavigationManager onControllerPushed(ThreadSlideController)
[D] 17:14:51.999 NavigationControllerContainerLayout initThreadControllerTracking()
[D] 17:14:52.000 ThreadLayout ThreadLayout.create(threadControllerType=Catalog)
[D] 17:14:52.026 CacheHandler diskCacheDir=/data/user/0/com.github.k1rakishou.chan.beta/files/disk_cache, totalFileCacheDiskSize=268.4 MB
[D] 17:14:52.028 InnerCache{0} cacheFileType=ThreadDownloaderThumbnail, fileCacheDiskSize=13.4 MB
[D] 17:14:52.028 InnerCache{0} recalculateSize() start
[D] 17:14:52.029 InnerCache{0} recalculateSize() end took 270.26us, filesOnDiskCount=0, fullyDownloadedFilesCount=0
[D] 17:14:52.029 InnerCache{0} clearChunksCacheDirInternal() start
[D] 17:14:52.029 InnerCache{0} clearChunksCacheDirInternal() end
[D] 17:14:52.030 InnerCache{1} cacheFileType=BookmarkThumbnail, fileCacheDiskSize=13.4 MB
[D] 17:14:52.030 InnerCache{1} recalculateSize() start
[D] 17:14:52.031 InnerCache{2} cacheFileType=NavHistoryThumbnail, fileCacheDiskSize=13.4 MB
[D] 17:14:52.031 InnerCache{2} recalculateSize() start
[D] 17:14:52.032 InnerCache{3} cacheFileType=SiteIcon, fileCacheDiskSize=13.4 MB
[D] 17:14:52.032 InnerCache{3} recalculateSize() start
[D] 17:14:52.033 InnerCache{4} cacheFileType=PostMediaThumbnail, fileCacheDiskSize=13.4 MB
[D] 17:14:52.034 InnerCache{4} recalculateSize() start
[D] 17:14:52.035 InnerCache{5} cacheFileType=PostMediaFull, fileCacheDiskSize=174.5 MB
[D] 17:14:52.035 InnerCache{5} recalculateSize() start
[D] 17:14:52.037 InnerCache{6} cacheFileType=Other, fileCacheDiskSize=26.8 MB
[D] 17:14:52.037 CacheHandler CacheHandler.init() took 26.009375ms
[D] 17:14:52.037 InnerCache{6} recalculateSize() start
[D] 17:14:52.039 NavigationControllerContainerLayout initBrowseControllerTracker()
[D] 17:14:52.040 NavigationControllerContainerLayout initThreadControllerTracking()
[D] 17:14:52.040 InnerCache{6} recalculateSize() end took 2.699375ms, filesOnDiskCount=2, fullyDownloadedFilesCount=0
[D] 17:14:52.040 InnerCache{6} clearChunksCacheDirInternal() start
[D] 17:14:52.040 InnerCache{6} clearChunksCacheDirInternal() end
[W] 17:14:52.040 ThreadPresenter isBound() currentChanDescriptor == null
[D] 17:14:52.041 ControllerNavigationManager onControllerSwipedTo(BrowseController)
[D] 17:14:52.043 StartActivity createUi took 100.203802ms
[D] 17:14:52.044 UpdateManager autoUpdateCheck()
[D] 17:14:52.044 UpdateManager autoUpdateCheck() isStableBuild(): false, isBetaBuild(): true, apkUpdateInfo: null
[D] 17:14:52.044 StartActivity initializeDependencies took 463.073us
[D] 17:14:52.044 StartActivityStartupHandlerHelper setupFromStateOrFreshLaunch(intent==null: false, savedInstanceState==null: true)
[D] 17:14:52.044 StartActivityStartupHandlerHelper onNewIntentInternal() -> false
[D] 17:14:52.044 StartActivityStartupHandlerHelper restoreFresh()
[D] 17:14:52.044 SiteManager SiteManager is not ready yet, waiting...
[D] 17:14:52.044 SiteManager SuspendableInitializer awaitUntilInitialized() called when not initialized, awaiting...
[D] 17:14:52.044 StartActivity onCreate() end isFreshStart: true
[D] 17:14:52.045 InnerCache{3} recalculateSize() end took 12.460937ms, filesOnDiskCount=35, fullyDownloadedFilesCount=0
[D] 17:14:52.045 InnerCache{3} clearChunksCacheDirInternal() start
[D] 17:14:52.045 InnerCache{3} clearChunksCacheDirInternal() end
[D] 17:14:52.046 Chan ^^^ App went foreground ^^^
[D] 17:14:52.046 ApplicationVisibilityManager onEnteredForeground() callback execution took 66.458us, callbacks count: 4
[W] 17:14:52.046 ThreadPresenter isBound() currentChanDescriptor == null
[D] 17:14:52.047 StartActivity start
[D] 17:14:52.105 BottomMenuPanel updatePaddings() state=NotInitialized
[D] 17:14:52.105 BottomMenuPanel updatePaddings() state=Hidden, visibility: 0, translationY=235.0
[D] 17:14:52.122 InnerCache{5} recalculateSize() end took 86.422396ms, filesOnDiskCount=270, fullyDownloadedFilesCount=0
[D] 17:14:52.122 InnerCache{5} clearChunksCacheDirInternal() start
[D] 17:14:52.122 InnerCache{5} clearChunksCacheDirInternal() end
[D] 17:14:52.139 AppModuleAndroidUtils waitForLayout requested a re-layout by returning false
[D] 17:14:52.142 ReplyLayoutViewModel onViewModelReady() threadControllerType: Catalog, instance: 100407460
[D] 17:14:52.143 UpdateManager runUpdateApi() manual=false
[D] 17:14:52.144 UpdateManager Calling update API for beta (https://api.github.com/repos/K1rakishou/Kuroba-Experimental-beta/releases/latest)
[E] 17:14:52.158 JsonReaderRequest Network request error
Exception title: IOException
Exception body: canceled due to java.lang.IllegalStateException: SiteManager is not ready yet! Use awaitUntilInitialized()java.io.IOException: canceled due to java.lang.IllegalStateException: SiteManager is not ready yet! Use awaitUntilInitialized()
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.lang.IllegalStateException: SiteManager is not ready yet! Use awaitUntilInitialized()
		at com.github.k1rakishou.chan.core.manager.SiteManager.firstActiveSiteOrNull(SourceFile:171)
		at com.github.k1rakishou.chan.core.site.SiteResolver.findSiteForUrl(Unknown Source:65)
		at com.github.k1rakishou.chan.core.base.okhttp.CloudFlareHandlerInterceptor.interceptInternal(SourceFile:34)
		at com.github.k1rakishou.chan.core.base.okhttp.CloudFlareHandlerInterceptor.intercept(SourceFile:1)
		at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:121)
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:97)
		at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:48)
		... 3 more


[E] 17:14:52.166 Chan Unhandled exception in thread: OkHttp Dispatcher
Exception title: IllegalStateException
Exception body: SiteManager is not ready yet! Use awaitUntilInitialized()java.lang.IllegalStateException: SiteManager is not ready yet! Use awaitUntilInitialized()
	at com.github.k1rakishou.chan.core.manager.SiteManager.firstActiveSiteOrNull(SourceFile:171)
	at com.github.k1rakishou.chan.core.site.SiteResolver.findSiteForUrl(Unknown Source:65)
	at com.github.k1rakishou.chan.core.base.okhttp.CloudFlareHandlerInterceptor.interceptInternal(SourceFile:34)
	at com.github.k1rakishou.chan.core.base.okhttp.CloudFlareHandlerInterceptor.intercept(SourceFile:1)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:121)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:97)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


[D] 17:14:52.167 ReplyManager restoreDrafts() done, draftsCount=16
[D] 17:14:52.167 ReplyManager reloadFilesFromDisk() restoreDrafts() took 25.313177ms
[D] 17:14:52.170 ReplyManager reloadFilesFromDisk() reloadAllFilesFromDisk() took 2.904375ms
[D] 17:14:52.170 filesLoadedInitializer SuspendableInitializer initWithValue() called
[D] 17:14:52.170 filesLoadedInitializer notifyAllWaiters throwable==null: true, waiters=0
[D] 17:14:52.170 filesLoadedInitializer SuspendableInitializer initWithValue() done
[D] 17:14:52.230 BookmarksRepository initialize() -> 3640 took 270.272552ms
[D] 17:14:52.233 ChanFilterManager SuspendableInitializer initWithValue() called
[D] 17:14:52.233 ChanFilterManager notifyAllWaiters throwable==null: true, waiters=0
[D] 17:14:52.234 ChanFilterManager SuspendableInitializer initWithValue() done
[D] 17:14:52.234 ChanFilterManager loadFiltersInternal() done. Loaded 19 filters
[D] 17:14:52.234 BookmarksManager SuspendableInitializer initWithValue() called
[D] 17:14:52.234 ChanFilterManager loadFiltersInternal() end, took 315.596145ms
[D] 17:14:52.234 BookmarksManager notifyAllWaiters throwable==null: true, waiters=0
[D] 17:14:52.234 BookmarksManager SuspendableInitializer initWithValue() done
[D] 17:14:52.237 SiteRepository initializeSites() -> 28 took 3.513646ms
[D] 17:14:52.238 allSitesLoadedInitializer SuspendableInitializer initWithModularResult() called
[D] 17:14:52.238 allSitesLoadedInitializer SuspendableInitializer initWithValue() called
[D] 17:14:52.238 allSitesLoadedInitializer notifyAllWaiters throwable==null: true, waiters=0
[D] 17:14:52.238 allSitesLoadedInitializer SuspendableInitializer initWithValue() done
[D] 17:14:52.238 SiteRepository allSitesLoadedInitializer initialized
[D] 17:14:52.244 BookmarksManager initializeBookmarksInternal() done. Loaded 3640 bookmarks and 6 active bookmarks
[D] 17:14:52.244 LynxchanSite Using domain: 'https://yeshoney.xyz/'
[D] 17:14:52.245 BookmarksManager initializeBookmarksInternal() end, took 327.059219ms
[D] 17:14:52.250 LynxchanSite Using domain: 'https://kohlchan.net/'
[D] 17:14:52.258 ChanPostRepository Not enough threads to start deleting, threads in database amount: 10919, max allowed threads amount: 12500
[D] 17:14:52.259 LynxchanSite Using domain: 'https://endchan.net/'
[D] 17:14:52.260 ChanPostRepository SuspendableInitializer initWithValue() called
[D] 17:14:52.261 ChanPostRepository notifyAllWaiters throwable==null: true, waiters=0
[D] 17:14:52.261 ChanPostRepository SuspendableInitializer initWithValue() done
[E] 17:14:52.262 SiteManager Unknown site descriptor: SD{yuki.la}
[E] 17:14:52.270 SiteManager Unknown site descriptor: SD{archive.rebeccablacktech.com}
[D] 17:14:52.284 Dvach Using domain: 'https://2ch.hk/'
[D] 17:14:52.293 SiteManager SuspendableInitializer initWithValue() called
[D] 17:14:52.295 BoardManager loadBoardsInternal() siteDataListAsync.get() end
[D] 17:14:52.295 SiteManager notifyAllWaiters throwable==null: true, waiters=0
[D] 17:14:52.295 SiteManager SuspendableInitializer initWithValue() done
[D] 17:14:52.295 SiteManager siteRepository.initializeSites() done. Loaded 28 sites
[D] 17:14:52.295 SiteManager loadSitesInternal() end, took 378.099948ms
[D] 17:14:52.305 BoardRepository loadAllBoards() -> 201 took 9.177344ms
[D] 17:14:52.306 BoardManager SuspendableInitializer initWithValue() called
[D] 17:14:52.306 BoardManager notifyAllWaiters throwable==null: true, waiters=0
[D] 17:14:52.306 BoardManager SuspendableInitializer initWithValue() done
[D] 17:14:52.306 BoardManager loadBoardsInternal() done. Loaded 201 boards
[D] 17:14:52.306 BoardManager loadBoardsInternal() end, took 389.425104ms
[D] 17:14:52.337 BookmarkBackgroundWatcherWorker BookmarkBackgroundWatcherWorker.doWork() Cannot start BookmarkWatcherDelegate, app is in foreground
[D] 17:14:52.337 BookmarkForegroundWatcher startWatchingIfNotWatchingYet() currentWorkJob is null or not active
[E] 17:14:52.338 UpdateManager Unknown error while trying to get new release apk
Exception title: IOException
Exception body: canceled due to java.lang.IllegalStateException: SiteManager is not ready yet! Use awaitUntilInitialized()java.io.IOException: canceled due to java.lang.IllegalStateException: SiteManager is not ready yet! Use awaitUntilInitialized()
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.lang.IllegalStateException: SiteManager is not ready yet! Use awaitUntilInitialized()
		at com.github.k1rakishou.chan.core.manager.SiteManager.firstActiveSiteOrNull(SourceFile:171)
		at com.github.k1rakishou.chan.core.site.SiteResolver.findSiteForUrl(Unknown Source:65)
		at com.github.k1rakishou.chan.core.base.okhttp.CloudFlareHandlerInterceptor.interceptInternal(SourceFile:34)
		at com.github.k1rakishou.chan.core.base.okhttp.CloudFlareHandlerInterceptor.intercept(SourceFile:1)
		at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:121)
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:97)
		at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:48)
		... 3 more


[E] 17:14:52.338 UpdateManager failedUpdate() manual=false
Exception title: IOException
Exception body: canceled due to java.lang.IllegalStateException: SiteManager is not ready yet! Use awaitUntilInitialized()java.io.IOException: canceled due to java.lang.IllegalStateException: SiteManager is not ready yet! Use awaitUntilInitialized()
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.lang.IllegalStateException: SiteManager is not ready yet! Use awaitUntilInitialized()
		at com.github.k1rakishou.chan.core.manager.SiteManager.firstActiveSiteOrNull(SourceFile:171)
		at com.github.k1rakishou.chan.core.site.SiteResolver.findSiteForUrl(Unknown Source:65)
		at com.github.k1rakishou.chan.core.base.okhttp.CloudFlareHandlerInterceptor.interceptInternal(SourceFile:34)
		at com.github.k1rakishou.chan.core.base.okhttp.CloudFlareHandlerInterceptor.intercept(SourceFile:1)
		at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:121)
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:97)
		at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:48)
		... 3 more


[E] 17:14:52.338 UpdateManager Failed to process beta API call for updating
[D] 17:14:52.356 FilterWatcherCoordinator chanFilterManager.listenForFiltersChanges() new filterEvent
[D] 17:14:52.361 BookmarksManager persistBookmarks async called
[D] 17:14:52.374 ThreadBookmarkLocalSource persist(3640)
[D] 17:14:52.412 InnerCache{2} recalculateSize() end took 380.575677ms, filesOnDiskCount=1838, fullyDownloadedFilesCount=0
[D] 17:14:52.412 InnerCache{2} clearChunksCacheDirInternal() start
[D] 17:14:52.416 InnerCache{2} clearChunksCacheDirInternal() end
[D] 17:14:52.439 InnerCache{1} recalculateSize() end took 409.213125ms, filesOnDiskCount=1589, fullyDownloadedFilesCount=0
[D] 17:14:52.440 InnerCache{1} clearChunksCacheDirInternal() start
[D] 17:14:52.440 InnerCache{1} clearChunksCacheDirInternal() end
[D] 17:14:52.463 ThreadBookmarkLocalSource persist() toInsertOrUpdateBookmarkReplyEntities: 60, toInsertOrUpdateThreadBookmarkEntities: 51
[D] 17:14:52.463 ThreadBookmarkLocalSource persist() inserted/updated 51 bookmarks, deleted 0 bookmarks
[D] 17:14:52.464 BookmarksRepository persist(3640) took 89.801771ms
[D] 17:14:52.484 InnerCache{4} recalculateSize() end took 450.087448ms, filesOnDiskCount=3041, fullyDownloadedFilesCount=0
[D] 17:14:52.484 InnerCache{4} clearChunksCacheDirInternal() start
[D] 17:14:52.485 InnerCache{4} clearChunksCacheDirInternal() end
[D] 17:14:52.571 AppConstants userAgent() Using default WebView user agent: 'Mozilla/5.0 (Linux; Android 13; M2101K9G Build/TKQ1.220829.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36'
[D] 17:14:52.572 SiteManager SuspendableInitializer awaitUntilInitialized() called when not initialized, done (diffTime=528ms)
[D] 17:14:52.572 SiteManager SiteManager initialization completed, took 527.771563ms
[D] 17:14:52.572 StartActivityStartupHandlerHelper getCatalogToOpen(), loadLastOpenedBoardUponAppStart=true
[D] 17:14:52.577 BookmarkForegroundWatcher channel.consumeEach() cancelling previous coroutine
[D] 17:14:52.577 BookmarkForegroundWatcher channel.consumeEach() starting new coroutine
[D] 17:14:52.577 BookmarkForegroundWatcher Got Foreground event, trying to restart the foreground watcher
[D] 17:14:52.577 BookmarkForegroundWatcher startWatchingIfNotWatchingYet() currentWorkJob is not null or is active
[D] 17:14:52.577 BookmarkWatcherCoordinator restartBackgroundWork() called tag=BookmarkWatcherController_Beta
[D] 17:14:52.578 BookmarkForegroundWatcher channel.consumeEach() working == true, calling updateBookmarksWorkerLoop()
[D] 17:14:52.580 BookmarkWatcherCoordinator restartBackgroundWork() called tag=BookmarkWatcherController_Beta
[D] 17:14:52.595 BookmarkWatcherCoordinator restartBackgroundWork() enqueued work with tag BookmarkWatcherController_Beta, backgroundIntervalMillis=900000
[D] 17:14:52.613 BookmarkWatcherCoordinator restartBackgroundWork() enqueued work with tag BookmarkWatcherController_Beta, backg

**Comment by K1rakishou** [comment]
The crash is fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/aced639562778e3fffd3f0dc937eeba9de4b0885

The slow app start might be because you have 3k bookmarks.

**Comment by cdr9042** [comment]
I've cleared all bookmarks, I still get stuck at the loading screen sometimes

**Comment by K1rakishou** [comment]
Can you send me your database backup? The email is on my Github profile page.
