### ISSUE TITLE
"You can't report posts because you are banned"

### ISSUE THREAD

**Issue by frozenpandaman** [K1rakishou/Kuroba-Experimental#901]
Same as #719 but figured I should open a new issue as that one is from over a year ago & closed for inactivity.

I constantly get this message even though I am not banned – every time I want to report a post, I need to click "open in webview" and use that form to make it work (kind of a pain because the CAPTCHA solver doesn't work there). I'm guessing this information is getting (incorrectly, for too long a period of time) cached somewhere?

Thanks!

Android API Level: 30 (Android 11)
App Version: v1.3.23

**Comment by frozenpandaman** [comment]
This is still occurring.

**Comment by K1rakishou** [comment]
Should be (hopefully) fixed by https://github.com/K1rakishou/Kuroba-Experimental/commit/d61c96d883a5af8f1649c46807f25f723ece9304

**Comment by frozenpandaman** [comment]
@K1rakishou I'm still getting this on  v1.3.27 (commit 4f950407b615), FYI.
